source:      .
destination: ./_site

timezone: Asia/Calcutta

url: http://localhost:4000
port: 4000
host: 0.0.0.0
baseurl: /

cursor:
  Title: "pravj | cursor"
  Person: "Pravendra Singh"
  Quote: "waiting for the end.."