# paste this in your _config.yml
# and edit these fields as well
cursor:
  # -- Title you want for page --
  Title: "--Title--"
  # -- Person's Name --
  Person: "--Person--"
  # -- Line whatever you want to add there --
  Quote: "-- Quote --"